In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [4]:
df.fuel_type.describe()

count        10000
unique           3
top       Gasoline
freq          6913
Name: fuel_type, dtype: object

In [5]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [6]:
df[df["origin"] == "Asia"].fuel_efficiency_mpg.max()

np.float64(41.2)

In [7]:
df.horsepower.median()

np.float64(254.0)

In [8]:
df.horsepower.mode()[0]

np.float64(252.0)

In [9]:
df2 = df.copy()

In [10]:
df2.horsepower = df2.horsepower.fillna(df2.horsepower.mode()[0])
df2.horsepower

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [11]:
df2.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [12]:
df2.horsepower.median()

np.float64(252.0)

In [13]:
df[df["origin"] == "Asia"]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [14]:
df[["vehicle_weight", "model_year"]][df["origin"] == "Asia"]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [15]:
df[["vehicle_weight", "model_year"]][df["origin"] == "Asia"].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [16]:
X = df[["vehicle_weight", "model_year"]][df["origin"] == "Asia"].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [17]:
X.T

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [18]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [19]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [20]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [21]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [22]:
np.linalg.inv(XTX)

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [23]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [25]:
#w = matrix_matrix_multiplication(matrix_matrix_multiplication(np.linalg.inv(XTX), X.T), y)
w = np.linalg.inv(XTX).dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [26]:
w.sum()

np.float64(0.36919696904925486)